name: mcp-manager

services:
  crawl4ai:
    image: unclecode/crawl4ai:0.8.0
    container_name: crawl4ai
    env_file:
      - .env
    shm_size: 1gb
    restart: unless-stopped
    networks:
      - mcp-manager-network

  searxng:
    image: searxng/searxng:2026.3.6-0716de6bc
    container_name: searxng
    env_file:
      - .env
    volumes:
      - ./config/:/etc/searxng/
      - ./data/:/var/cache/searxng/
    restart: unless-stopped
    networks:
      - mcp-manager-network

  mcp-manager:
    build:
      context: .
      dockerfile: Dockerfile.mcp-manager
    container_name: mcp-manager
    env_file:
      - .env
    ports:
      - "${MCP_MANAGER_PORT:-8000}:${MCP_MANAGER_PORT:-8000}"
    restart: unless-stopped
    networks:
      - mcp-manager-network

networks:
  mcp-manager-network:
    driver: bridge
    name: mcp-manager-network
    # add subnet for custom network
    ipam:
      config:
        # different docker compose need to set different subnet to avoid conflict
        - subnet: 10.200.1.0/24
