name: searxng

services:
  searxng:
    image: searxng/searxng:2026.3.6-0716de6bc
    container_name: searxng
    ports:
      - "8888:8080"
    volumes:
      - ./config/:/etc/searxng/
      - ./data/:/var/cache/searxng/
    restart: unless-stopped
